// This file is generated by icon spritesheet generator

export const iconNames = [
  "update",
  "sun",
  "moon",
  "laptop",
  "cross-1",
  "chevron-right",
  "check",
] as const

export type IconName = typeof iconNames[number]
