import { describe, it, expect, vi, beforeEach } from "vitest";

const mockInvitationCreate = vi.fn();
const mockInvitationFindUnique = vi.fn();
const mockInvitationFindMany = vi.fn();
const mockInvitationUpdate = vi.fn();
const mockUserRoleCreate = vi.fn();

vi.mock("~/lib/db/db.server", () => ({
  prisma: {
    invitation: {
      create: (...args: unknown[]) => mockInvitationCreate(...args),
      findUnique: (...args: unknown[]) => mockInvitationFindUnique(...args),
      findMany: (...args: unknown[]) => mockInvitationFindMany(...args),
      update: (...args: unknown[]) => mockInvitationUpdate(...args),
    },
    userRole: {
      create: (...args: unknown[]) => mockUserRoleCreate(...args),
    },
  },
}));

const mockSendEmail = vi.fn();
vi.mock("~/lib/email/email.server", () => ({
  sendEmail: (...args: unknown[]) => mockSendEmail(...args),
}));

const mockInvitationEmail = vi.fn();
vi.mock("~/lib/email/email-templates.server", () => ({
  invitationEmail: (...args: unknown[]) => mockInvitationEmail(...args),
}));

vi.mock("~/lib/monitoring/logger.server", () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));

describe("invitations.server", () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  // ─── createInvitation ───────────────────────────────────

  describe("createInvitation", () => {
    it("creates an invitation, sends email, and returns invitation with relations", async () => {
      const { createInvitation } = await import("~/services/invitations.server");
      const mockInvitation = {
        id: "inv-1",
        email: "alice@example.com",
        tenantId: "t-1",
        roleIds: ["role-1", "role-2"],
        token: "random-hex-token",
        invitedById: "u-admin",
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        status: "PENDING",
        tenant: { name: "Acme Corp" },
        invitedBy: { name: "Admin User", email: "admin@example.com" },
      };
      mockInvitationCreate.mockResolvedValue(mockInvitation);
      mockInvitationEmail.mockReturnValue({
        subject: "You are invited",
        html: "<p>Join us</p>",
        text: "Join us",
      });
      mockSendEmail.mockResolvedValue({ id: "email-1" });

      const result = await createInvitation({
        email: "alice@example.com",
        tenantId: "t-1",
        roleIds: ["role-1", "role-2"],
        invitedById: "u-admin",
      });

      expect(result).toEqual(mockInvitation);
      expect(mockInvitationCreate).toHaveBeenCalledWith({
        data: expect.objectContaining({
          email: "alice@example.com",
          tenantId: "t-1",
          roleIds: ["role-1", "role-2"],
          invitedById: "u-admin",
          token: expect.any(String),
          expiresAt: expect.any(Date),
        }),
        include: {
          tenant: { select: { name: true } },
          invitedBy: { select: { name: true, email: true } },
        },
      });
      expect(mockInvitationEmail).toHaveBeenCalledWith(
        expect.any(String),
        "Acme Corp",
        "Admin User",
      );
      // Token is generated by crypto.randomBytes, so verify it's a 64-char hex string
      const actualToken = mockInvitationEmail.mock.calls[0][0] as string;
      expect(actualToken).toMatch(/^[a-f0-9]{64}$/);
      expect(mockSendEmail).toHaveBeenCalledWith({
        to: "alice@example.com",
        subject: "You are invited",
        html: "<p>Join us</p>",
        text: "Join us",
      });
    });

    it("uses inviter email when inviter name is empty", async () => {
      const { createInvitation } = await import("~/services/invitations.server");
      const mockInvitation = {
        id: "inv-2",
        email: "bob@example.com",
        tenantId: "t-1",
        roleIds: ["role-1"],
        token: "abc123",
        invitedById: "u-admin",
        expiresAt: new Date(),
        status: "PENDING",
        tenant: { name: "Acme Corp" },
        invitedBy: { name: "", email: "admin@example.com" },
      };
      mockInvitationCreate.mockResolvedValue(mockInvitation);
      mockInvitationEmail.mockReturnValue({
        subject: "Invite",
        html: "<p>Hi</p>",
        text: "Hi",
      });
      mockSendEmail.mockResolvedValue({ id: "email-2" });

      await createInvitation({
        email: "bob@example.com",
        tenantId: "t-1",
        roleIds: ["role-1"],
        invitedById: "u-admin",
      });

      expect(mockInvitationEmail).toHaveBeenCalledWith(
        expect.any(String),
        "Acme Corp",
        "admin@example.com",
      );
    });

    it("does not throw when sendEmail fails", async () => {
      const { createInvitation } = await import("~/services/invitations.server");
      const mockInvitation = {
        id: "inv-3",
        email: "fail@example.com",
        tenantId: "t-1",
        roleIds: [],
        token: "xyz789",
        invitedById: "u-admin",
        expiresAt: new Date(),
        status: "PENDING",
        tenant: { name: "Acme Corp" },
        invitedBy: { name: "Admin", email: "admin@example.com" },
      };
      mockInvitationCreate.mockResolvedValue(mockInvitation);
      mockInvitationEmail.mockReturnValue({
        subject: "Invite",
        html: "<p>Hi</p>",
        text: "Hi",
      });
      mockSendEmail.mockRejectedValue(new Error("SMTP down"));

      const result = await createInvitation({
        email: "fail@example.com",
        tenantId: "t-1",
        roleIds: [],
        invitedById: "u-admin",
      });

      // Should still return the invitation even though email failed
      expect(result).toEqual(mockInvitation);
    });

    it("sets expiration to 7 days from now", async () => {
      const { createInvitation } = await import("~/services/invitations.server");
      const now = Date.now();
      mockInvitationCreate.mockResolvedValue({
        id: "inv-4",
        email: "test@example.com",
        tenantId: "t-1",
        roleIds: [],
        token: "tok-4",
        invitedById: "u-admin",
        expiresAt: new Date(now + 7 * 24 * 60 * 60 * 1000),
        status: "PENDING",
        tenant: { name: "Test Org" },
        invitedBy: { name: "Admin", email: "admin@test.org" },
      });
      mockInvitationEmail.mockReturnValue({ subject: "s", html: "h", text: "t" });
      mockSendEmail.mockResolvedValue({ id: "e-4" });

      await createInvitation({
        email: "test@example.com",
        tenantId: "t-1",
        roleIds: [],
        invitedById: "u-admin",
      });

      const createArgs = mockInvitationCreate.mock.calls[0][0];
      const expiresAt = createArgs.data.expiresAt.getTime();
      const sevenDaysMs = 7 * 24 * 60 * 60 * 1000;
      // Allow a small delta for execution time
      expect(expiresAt).toBeGreaterThanOrEqual(now + sevenDaysMs - 5000);
      expect(expiresAt).toBeLessThanOrEqual(now + sevenDaysMs + 5000);
    });
  });

  // ─── getInvitationByToken ──────────────────────────────

  describe("getInvitationByToken", () => {
    it("returns the invitation with tenant data", async () => {
      const { getInvitationByToken } = await import("~/services/invitations.server");
      const mockInvitation = {
        id: "inv-1",
        token: "valid-token",
        status: "PENDING",
        tenant: { id: "t-1", name: "Acme Corp", slug: "acme" },
      };
      mockInvitationFindUnique.mockResolvedValue(mockInvitation);

      const result = await getInvitationByToken("valid-token");

      expect(result).toEqual(mockInvitation);
      expect(mockInvitationFindUnique).toHaveBeenCalledWith({
        where: { token: "valid-token" },
        include: {
          tenant: { select: { id: true, name: true, slug: true } },
        },
      });
    });

    it("returns null when token does not exist", async () => {
      const { getInvitationByToken } = await import("~/services/invitations.server");
      mockInvitationFindUnique.mockResolvedValue(null);

      const result = await getInvitationByToken("nonexistent-token");

      expect(result).toBeNull();
    });
  });

  // ─── acceptInvitation ──────────────────────────────────

  describe("acceptInvitation", () => {
    it("accepts a valid pending invitation and assigns roles", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      const futureDate = new Date(Date.now() + 24 * 60 * 60 * 1000);
      const mockInvitation = {
        id: "inv-1",
        token: "valid-token",
        status: "PENDING",
        roleIds: ["role-1", "role-2"],
        expiresAt: futureDate,
        tenantId: "t-1",
      };
      mockInvitationFindUnique.mockResolvedValue(mockInvitation);
      mockUserRoleCreate.mockResolvedValue({});
      mockInvitationUpdate.mockResolvedValue({ ...mockInvitation, status: "ACCEPTED" });

      const result = await acceptInvitation("valid-token", "u-new");

      expect(result).toEqual(mockInvitation);
      // Should create user roles for each roleId
      expect(mockUserRoleCreate).toHaveBeenCalledTimes(2);
      expect(mockUserRoleCreate).toHaveBeenCalledWith({
        data: { userId: "u-new", roleId: "role-1" },
      });
      expect(mockUserRoleCreate).toHaveBeenCalledWith({
        data: { userId: "u-new", roleId: "role-2" },
      });
      // Should mark invitation as accepted
      expect(mockInvitationUpdate).toHaveBeenCalledWith({
        where: { id: "inv-1" },
        data: { status: "ACCEPTED" },
      });
    });

    it("throws when invitation is not found", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      mockInvitationFindUnique.mockResolvedValue(null);

      await expect(acceptInvitation("bad-token", "u-1")).rejects.toThrow("Invalid invitation");
    });

    it("throws when invitation is already accepted", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      mockInvitationFindUnique.mockResolvedValue({
        id: "inv-1",
        token: "used-token",
        status: "ACCEPTED",
        roleIds: [],
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
      });

      await expect(acceptInvitation("used-token", "u-1")).rejects.toThrow("Invalid invitation");
    });

    it("throws when invitation is revoked", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      mockInvitationFindUnique.mockResolvedValue({
        id: "inv-1",
        token: "revoked-token",
        status: "REVOKED",
        roleIds: [],
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
      });

      await expect(acceptInvitation("revoked-token", "u-1")).rejects.toThrow(
        "Invalid invitation",
      );
    });

    it("throws and marks invitation as expired when past expiry", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      const pastDate = new Date(Date.now() - 24 * 60 * 60 * 1000);
      mockInvitationFindUnique.mockResolvedValue({
        id: "inv-expired",
        token: "expired-token",
        status: "PENDING",
        roleIds: ["role-1"],
        expiresAt: pastDate,
      });
      mockInvitationUpdate.mockResolvedValue({});

      await expect(acceptInvitation("expired-token", "u-1")).rejects.toThrow(
        "Invitation has expired",
      );

      // Should update the status to EXPIRED
      expect(mockInvitationUpdate).toHaveBeenCalledWith({
        where: { id: "inv-expired" },
        data: { status: "EXPIRED" },
      });
      // Should NOT assign any roles
      expect(mockUserRoleCreate).not.toHaveBeenCalled();
    });

    it("skips duplicate role assignment gracefully", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      const futureDate = new Date(Date.now() + 24 * 60 * 60 * 1000);
      mockInvitationFindUnique.mockResolvedValue({
        id: "inv-dup",
        token: "dup-token",
        status: "PENDING",
        roleIds: ["role-1", "role-2"],
        expiresAt: futureDate,
      });
      // First role assignment succeeds, second fails (already assigned)
      mockUserRoleCreate
        .mockResolvedValueOnce({ userId: "u-1", roleId: "role-1" })
        .mockRejectedValueOnce(new Error("Unique constraint violation"));
      mockInvitationUpdate.mockResolvedValue({});

      // Should not throw even though one role creation fails
      const result = await acceptInvitation("dup-token", "u-1");

      expect(result.id).toBe("inv-dup");
      expect(mockUserRoleCreate).toHaveBeenCalledTimes(2);
      expect(mockInvitationUpdate).toHaveBeenCalledWith({
        where: { id: "inv-dup" },
        data: { status: "ACCEPTED" },
      });
    });

    it("accepts invitation with no roles", async () => {
      const { acceptInvitation } = await import("~/services/invitations.server");
      const futureDate = new Date(Date.now() + 24 * 60 * 60 * 1000);
      const mockInvitation = {
        id: "inv-noroles",
        token: "no-roles-token",
        status: "PENDING",
        roleIds: [],
        expiresAt: futureDate,
      };
      mockInvitationFindUnique.mockResolvedValue(mockInvitation);
      mockInvitationUpdate.mockResolvedValue({});

      const result = await acceptInvitation("no-roles-token", "u-1");

      expect(result).toEqual(mockInvitation);
      expect(mockUserRoleCreate).not.toHaveBeenCalled();
      expect(mockInvitationUpdate).toHaveBeenCalledWith({
        where: { id: "inv-noroles" },
        data: { status: "ACCEPTED" },
      });
    });
  });

  // ─── revokeInvitation ──────────────────────────────────

  describe("revokeInvitation", () => {
    it("revokes an invitation by id and tenantId", async () => {
      const { revokeInvitation } = await import("~/services/invitations.server");
      mockInvitationUpdate.mockResolvedValue({
        id: "inv-1",
        status: "REVOKED",
        tenantId: "t-1",
      });

      const result = await revokeInvitation("inv-1", "t-1");

      expect(result.status).toBe("REVOKED");
      expect(mockInvitationUpdate).toHaveBeenCalledWith({
        where: { id: "inv-1", tenantId: "t-1" },
        data: { status: "REVOKED" },
      });
    });

    it("throws when invitation does not exist or wrong tenant", async () => {
      const { revokeInvitation } = await import("~/services/invitations.server");
      mockInvitationUpdate.mockRejectedValue(new Error("Record to update not found."));

      await expect(revokeInvitation("inv-999", "t-wrong")).rejects.toThrow(
        "Record to update not found.",
      );
    });
  });

  // ─── getInvitations ────────────────────────────────────

  describe("getInvitations", () => {
    it("returns all invitations for a tenant ordered by createdAt desc", async () => {
      const { getInvitations } = await import("~/services/invitations.server");
      const mockInvitations = [
        {
          id: "inv-2",
          email: "bob@example.com",
          status: "PENDING",
          createdAt: new Date("2025-02-01"),
          invitedBy: { name: "Admin", email: "admin@example.com" },
        },
        {
          id: "inv-1",
          email: "alice@example.com",
          status: "ACCEPTED",
          createdAt: new Date("2025-01-01"),
          invitedBy: { name: "Admin", email: "admin@example.com" },
        },
      ];
      mockInvitationFindMany.mockResolvedValue(mockInvitations);

      const result = await getInvitations("t-1");

      expect(result).toHaveLength(2);
      expect(result[0].id).toBe("inv-2");
      expect(mockInvitationFindMany).toHaveBeenCalledWith({
        where: { tenantId: "t-1" },
        include: {
          invitedBy: { select: { name: true, email: true } },
        },
        orderBy: { createdAt: "desc" },
      });
    });

    it("returns empty array when no invitations exist", async () => {
      const { getInvitations } = await import("~/services/invitations.server");
      mockInvitationFindMany.mockResolvedValue([]);

      const result = await getInvitations("t-empty");

      expect(result).toEqual([]);
    });
  });
});
