// Generated by React Router

import 'react-router'

declare module 'react-router' {
	interface Register {
		pages: Pages
		routeFiles: RouteFiles
	}
}

type Pages = {
	'/': {
		params: {}
	}
	'/*': {
		params: {
			'*': string
		}
	}
	'/forgot-password': {
		params: {}
	}
	'/login': {
		params: {}
	}
	'/logout': {
		params: {}
	}
	'/onboarding': {
		params: {}
	}
	'/reset-password': {
		params: {}
	}
	'/signup': {
		params: {}
	}
	'/verify': {
		params: {}
	}
	'/home': {
		params: {}
	}
	'/resources/theme-switch': {
		params: {}
	}
}

type RouteFiles = {
	'root.tsx': {
		id: 'root'
		page:
			| '/'
			| '/*'
			| '/forgot-password'
			| '/login'
			| '/logout'
			| '/onboarding'
			| '/reset-password'
			| '/signup'
			| '/verify'
			| '/home'
			| '/resources/theme-switch'
	}
	'routes/$.tsx': {
		id: 'routes/$'
		page: '/*'
	}
	'routes/_auth+/forgot-password.tsx': {
		id: 'routes/_auth+/forgot-password'
		page: '/forgot-password'
	}
	'routes/_auth+/login.tsx': {
		id: 'routes/_auth+/login'
		page: '/login'
	}
	'routes/_auth+/logout.tsx': {
		id: 'routes/_auth+/logout'
		page: '/logout'
	}
	'routes/_auth+/onboarding.tsx': {
		id: 'routes/_auth+/onboarding'
		page: '/onboarding'
	}
	'routes/_auth+/reset-password.tsx': {
		id: 'routes/_auth+/reset-password'
		page: '/reset-password'
	}
	'routes/_auth+/signup.tsx': {
		id: 'routes/_auth+/signup'
		page: '/signup'
	}
	'routes/_auth+/verify.tsx': {
		id: 'routes/_auth+/verify'
		page: '/verify'
	}
	'routes/home.tsx': {
		id: 'routes/home'
		page: '/home'
	}
	'routes/index.tsx': {
		id: 'routes/index'
		page: '/'
	}
	'routes/resources+/theme-switch.tsx': {
		id: 'routes/resources+/theme-switch'
		page: '/resources/theme-switch'
	}
}
