// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/resources/theme-switch": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/resources/theme-switch";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/resources+/theme-switch.tsx": {
    id: "routes/resources+/theme-switch";
    page: "/resources/theme-switch";
  };
};